baedal-project/baedal

src/main/java/com/example/baedal/BaedalApplication.java, src/main/java/com/example/baedal/controller/LikeController.java, src/main/java/com/example/baedal/domain/Likes.java, src/main/java/com/example/baedal/domain/Member.java, src/main/java/com/example/baedal/domain/OrderHasItem.java, src/main/java/com/example/baedal/domain/Store.java, src/main/java/com/example/baedal/dto/request/LikeRequestDto.java, src/main/java/com/example/baedal/repository/LikeRepository.java, src/main/java/com/example/baedal/repository/StoreRepository.java, src/main/java/com/example/baedal/service/LikeService.java, src/main/java/com/example/baedal/service/OrderService.java
-#2
가게 추천 기능 추가 및 평균 평점 구하는 메소드 추가하였습니다
가게 평점 double로 randomly created 됩니다.
=> post : like, avg 기능 추가

src/main/java/com/example/baedal/controller/SearchController.java, src/main/java/com/example/baedal/dto/request/SearchRequestDto.java, src/main/java/com/example/baedal/repository/StoreRepository.java, src/main/java/com/example/baedal/service/SearchService.java
간단한 검색 API
- 검색 API 구현 
{
"keyword": "검색어",
"memberId": 멤버Id
}
=> feat : 멤버 주소별 음식점 이름 검색 API

src/main/java/com/example/baedal/controller/OrderController.java, src/main/java/com/example/baedal/domain/Item.java, src/main/java/com/example/baedal/domain/Likes.java, src/main/java/com/example/baedal/domain/OrderHasItem.java, src/main/java/com/example/baedal/domain/Orders.java, src/main/java/com/example/baedal/dto/response/OrderResponseDto.java, src/main/java/com/example/baedal/service/LikeService.java, src/main/java/com/example/baedal/service/MemberService.java, src/main/java/com/example/baedal/service/OrderService.java, src/main/java/com/example/baedal/service/StoreService.java
-#2
1. orderHasitems에 amount field 추가
2. orderRequestDto에 amount 추가
3. orderResponseDto class 추가
4. orderService postLike response 변경
=> feat : orderhasitem amount 추가

docker/docker-compose.yml
구축된 DB에 대한 예시 docker-compose.yml파일 업로드
- MySQL DB 구축
- PostgreSQL DB 구축
docker-compose.yml 작성
=> feat : DB 구축 docker-compose.yml 작성

.github/workflows/deploy.yml, CD/deploy.sh, src/main/java/com/example/baedal/config/WebConfig.java
main브랜치 서버 자동배포
- 원격지에서 pull 후 빌드 실행하는 스크립트 작성 #20 
- 자동 배포용 Github Actions 스크립트 작성 #19
=> feat : 자동배포 스크립트 작성

src/main/java/com/example/baedal/domain/Store.java
mag: fix/store
store 테이블 타입변경
category컬럼 enum에서 String타입으로 변경
=> fix : store 테이블 category컬럼 enum > string 타입으로 변경

src/main/java/com/example/baedal/dto/request/OrderRequestDto.java, src/main/java/com/example/baedal/dto/response/OrderResponseDto.java, src/main/java/com/example/baedal/service/OrderService.java
-
item에 따른 amount를 다르게 갖도록 변경하였습니다.
request, response 둘 다 List 형태로 요청, 반환 됩니다.
=> fix : item마다 amount 가질 수 있도록 변경

README.md
=> docs : README 작성

CD/deploy.sh
Github Actions 실행 시 실행로그가 찍히는 문제가 있음
스크립트 수정
=> fix : Actions에 로그 찍히는 문제 해결

.github/workflows/deploy.yml, Dockerfile, build.gradle, docker/docker-compose.yml
Docker 방식으로 배포
- Dockerfile 추가
- Github registry이용하는 방법으로 구축
Issue: #18
=> feat : Docker 배포 자동화

src/test/java/com/example/baedal/BaedalApplicationTests.java
=> fix : 불필요한 테스트 제거

src/main/java/com/example/baedal/domain/Store.java
store의 likes 부분에 jsonignore추가
- likes를 Store가 하나하나씩 조회되는 문제가 발생(데이터가 52만개인데 하나씩 조회되면..)
- ignore로 불필요 데이터 조회 차단
=> fix : jsonignore 추가

src/main/java/com/example/baedal/controller/StoreController.java, src/main/java/com/example/baedal/service/StoreService.java
StoreList 페이징 처리
Controller, Service 페이징 관련 코드 추가
=> feat : StoreList 페이징 처리

.github/workflows/deploy.yml
Deploy 관련 리팩터링
- 각각 과정별 주석 추가
- 불필요 코드 제거
- Gradle 캐시 적용
=> refactor : deploy.yml 리팩터링

src/main/java/com/example/baedal/domain/Member.java, src/main/java/com/example/baedal/domain/Store.java, src/main/java/com/example/baedal/shared/Role.java
feat : member
member role 추가, store 연관관계추가
member role 추가, store 연관관계추가
=> feat : member role 추가 그에따른 store 연관관계 추가

src/main/java/com/example/baedal/controller/OrderController.java, src/main/java/com/example/baedal/domain/Item.java, src/main/java/com/example/baedal/domain/Orders.java, src/main/java/com/example/baedal/repository/OrderRepository/OrderRepositoryCustom.java, src/main/java/com/example/baedal/repository/OrderRepository/OrderRepositoryImpl.java, src/main/java/com/example/baedal/service/OrderService.java
=> refactor : orders paging 가능하게끔 처리(batch size)

src/main/java/com/example/baedal/controller/OrderController.java, src/main/java/com/example/baedal/service/OrderService.java
=> feat : Paging using JPA findAll(v3)

build.gradle, src/main/java/com/example/baedal/BaedalApplication.java, src/main/java/com/example/baedal/config/CorsConfig.java, src/main/java/com/example/baedal/config/JwtSecurityConfiguration.java, src/main/java/com/example/baedal/config/SecurityConfiguration.java, src/main/java/com/example/baedal/config/aop/LogAspect.java, src/main/java/com/example/baedal/config/aop/LogExecutionTime.java, src/main/java/com/example/baedal/controller/MemberController.java, src/main/java/com/example/baedal/controller/OrderController.java, src/main/java/com/example/baedal/domain/Item.java, src/main/java/com/example/baedal/domain/Member.java, src/main/java/com/example/baedal/domain/RefreshToken.java, src/main/java/com/example/baedal/dto/TokenDto.java, src/main/java/com/example/baedal/dto/request/LoginRequestDto.java, src/main/java/com/example/baedal/dto/request/MemberRequestDto.java, src/main/java/com/example/baedal/dto/response/MemberResponseDto.java, src/main/java/com/example/baedal/jwt/JwtFilter.java, src/main/java/com/example/baedal/jwt/TokenProvider.java, src/main/java/com/example/baedal/jwt/exception/AccessDeniedHandlerException.java, src/main/java/com/example/baedal/jwt/exception/AuthenticationEntryPointException.java, src/main/java/com/example/baedal/jwt/user/UserDetailsImpl.java, src/main/java/com/example/baedal/jwt/user/UserDetailsServiceImpl.java, src/main/java/com/example/baedal/repository/MemberRepository/MemberRepository.java, src/main/java/com/example/baedal/repository/MemberRepository/MemberRepositoryImpl.java, src/main/java/com/example/baedal/repository/RefreshTokenRepository.java, src/main/java/com/example/baedal/service/LikeService.java, src/main/java/com/example/baedal/service/MemberService.java, src/main/java/com/example/baedal/service/OrderService.java, src/main/java/com/example/baedal/shared/Category.java, src/main/java/com/example/baedal/shared/Role.java
-#31
Token 이용해서 login 하는 것으로 변경
=> feat : Authentication with token

.github/workflows/deploy.yml
=> feat: Deploy jobs

.github/workflows/Gradle_Test.yml, .github/workflows/deploy.yml
CD 시 TEST 진행하도록 변경
Github Actions 스크립트 변경
=> refactor: Add Test Task

.github/workflows/deploy.yml
Environments를 이용한 Dev서버와 Production 서버 배포 시나리오 설정
- Environments를 추가하여 Dev 서버에 먼저 배포하고 승인 후 Production 에 배포할 수 있도록 수정
=> feat: Add Environments

.github/workflows/Gradle_Test.yml, src/main/java/com/example/baedal/config/CorsConfig.java
CD과정 리팩터링
- Dev 서버 CORS에러 및 checkout과정 버전 업데이트
=> fix: Dev 서버 CORS에러 및 checkout과정 버전 업데이트

src/main/java/com/example/baedal/domain/Item.java, src/main/java/com/example/baedal/error/ErrorCode.java, src/main/java/com/example/baedal/service/OrderService.java
=> feat : 재고 처리 로직 추가

.github/workflows/deploy.yml
=> feat : Add Cloud Deploy

.github/workflows/deploy.yml
=> fix : Deploy 개선

.github/workflows/deploy.yml
=> fix : Deploy Bug
